### PR TITLE
update: added badge with icon component

### PR DESCRIPTION
**Pull request by Kothalkarpriya**
I have added files and the structure of the component library. Completed badge with icon

### CODE REVIEW

**Comment by mariyasada** [comment]
Code looks clean. Just one suggestion add comments.

**Comment by Kothalkarpriya** [comment]
> Code looks clean. Just one suggestion add comments.

Great. Thank you

**Comment by JantuDeb** [comment]
Use separate branches for components, [Go through this discord announcement](https://discord.com/channels/914867137863118919/918560683401039952/936161954563756154)
If this pull request is for documentation then you are good to go.

**Comment by Kothalkarpriya** [comment]
> Use separate branches for components, [Go through this discord announcement](https://discord.com/channels/914867137863118919/918560683401039952/936161954563756154) If this pull request is for documentation then you are good to go.

Yes, It is my first pull request, so it has the structure I wanted to have for my component library. From now only new feature changes will be there. 
Thank you

**Pull request merged**
