### PR TITLE
update: button feature added

### PR DESCRIPTION
**Pull request by Kothalkarpriya**
Different styling for button added with snippet

### CODE REVIEW

**Comment by Manju-sree** [comment]
Please try to use media queries.. rest code looks fine

**Comment by sks-21** [comment]
The code looks nice. Just one suggestion, it's a good practice to remove the unnecessary commented code.

**Review by tushartiwari7 — APPROVED** [review]
Good work! You can merge this.

**Comment by Kothalkarpriya** [comment]
> Please try to use media queries.. rest code looks fine

Ok Thank you

**Comment by Kothalkarpriya** [comment]
> The code looks nice. Just one suggestion, it's a good practice to remove the unnecessary commented code.

Okay Thanks I will remove unwanted comments

**Comment by Kothalkarpriya** [comment]
> Good work! You can merge this.

Thank you

**Pull request merged**
