### PR TITLE
Feature navigation

### PR DESCRIPTION
**Pull request by Kothalkarpriya**
I have added simple desktop navigation component

### CODE REVIEW

**Review by ajit-sharmaGH — APPROVED** [review]
everything looks fine, you can use html formatter before push

**Comment by Kothalkarpriya** [comment]
> everything looks fine, you can use html formatter before push

Yes, I will do it

**Review by JantuDeb — APPROVED** [review]
Looks good just format html before commit as @ajit-sharmaGH  said

**Comment by Kothalkarpriya** [comment]
> Looks good just format Html before commit as @ajit-sharmaGH said

Yes I will keep it in mind always

**Pull request merged**
