### PR TITLE
fix: issues with styling

### PR DESCRIPTION
**Pull request by Kothalkarpriya**
Removed similar styles, merged them and fixed issues

### CODE REVIEW

**Comment by psychoactiv** [comment]
Looks good you are good to go

**Review by sushil-mod — APPROVED** [review]
code looks better ,you can merge!

**Review by Nagashree01 — APPROVED** [review]
This looks good. But in alert also the texts are aligned in the center. Can you look into it

**Comment by Kothalkarpriya** [comment]
> This looks good. But in alert also the texts are aligned in the center. Can you look into it

Yes, I will definitely Improve it

**Pull request merged**
