### PR TITLE
update: input feature added

### PR DESCRIPTION
**Pull request by Kothalkarpriya**
I have added an input feature for text, password, and error input

### CODE REVIEW

**Comment by Bhakti199** [comment]
nice work priya, looks cool

**Comment by Kothalkarpriya** [comment]
> nice work priya, looks cool
Thank you

**Review by fahd23 — COMMENTED** [review]
Looks good, use code formatter like prettier so that reviewer can easily review the code

**Comment by Kothalkarpriya** [comment]
> Looks good, use code formatter like prettier so that reviewer can easily review the code

Yes, I will Thank you

**Pull request merged**
